[tools]
# Dependencies only; tasks are handled by the Justfile.
rust = "1.88.0"
# TinyGo 0.38.x requires Go 1.19–1.24; pin a compatible Go
go = "1.24.0"
just = "1.21.0"
tinygo = "0.38.0"
zig = "latest"

[alias]
# Map tools to asdf plugins so mise can auto-install
zig = "asdf:asdf-community/asdf-zig"
tinygo = "asdf:troyjfarrell/asdf-tinygo"
